-- MySQL --
-- Session --
CREATE TABLE IF NOT EXISTS `session` (`token` VARCHAR(255) NOT NULL COMMENT 'ワンタイムトークン', `created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'トークン作成日時', PRIMARY KEY(`token`)) ENGINE = MYISAM COMMENT='セッションテーブル';
CREATE TABLE IF NOT EXISTS `sessiondata` (`identifier` VARCHAR(96) NOT NULL COMMENT 'deviceテーブルのPkey', `data` TEXT DEFAULT NULL COMMENT 'jsonシリアライズされたセッションデータ', `modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '変更日時', PRIMARY KEY(`identifier`)) ENGINE = MYISAM COMMENT='セッションデータテーブル';
-- fwmUser --
CREATE TABLE IF NOT EXISTS `fwmuser` (`id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'pkey', `name` VARCHAR(1024) NOT NULL COMMENT '名前', `mail` VARCHAR(1024) NOT NULL COMMENT 'メールアドレス', `pass` VARCHAR(64) NOT NULL COMMENT 'パスワード(SHA256)', PRIMARY KEY(`id`)) ENGINE=InnoDB COMMENT='ユーザーテーブル';
-- User --
CREATE TABLE IF NOT EXISTS `device` (`udid` CHAR(36) NOT NULL COMMENT 'udid(pkey)', `owner_id` int(11) NOT NULL DEFAULT 0 COMMENT 'レコードオーナー(userテーブルのPkey)', `type` VARCHAR(10) NOT NULL DEFAULT 'PC' COMMENT 'デバイスタイプ(PC,iPhone,Android...)', `version_name` VARCHAR(10) COMMENT '表示バージョン', `version_code` VARCHAR(10) COMMENT '内部バージョン', `device_token` CHAR(255) DEFAULT NULL COMMENT 'デバイストークン', `sandbox_enabled` char(1) NOT NULL DEFAULT '0' COMMENT 'iOS SANDBOX環境APNS用フラグ', `created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '作成日時', `modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '更新日時', `available` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'レコード有効状態(0:無効 1:有効)', PRIMARY KEY(`udid`)) ENGINE=InnoDB COMMENT='デバイステーブル';
CREATE TABLE IF NOT EXISTS `user` (`id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'pkey', `name` VARCHAR(128) DEFAULT NULL COMMENT 'ユーザー名称(ユーザー名)', `uniq_name` VARCHAR(128) DEFAULT NULL COMMENT 'user名(ユーザーID)', `created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '作成日時', `modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '更新日時', `available` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'レコード有効状態(0:無効 1:有効)', PRIMARY KEY(`id`)) ENGINE=InnoDB COMMENT='ユーザーテーブル';
CREATE TABLE IF NOT EXISTS `sample` (`id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'pkey', `name` VARCHAR(128) DEFAULT NULL COMMENT 'レコード名', `owner_id` int(11) NOT NULL COMMENT 'レコードオーナー(userテーブルのPkey)', `created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '作成日時', `modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '更新日時', `available` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'レコード有効状態(0:無効 1:有効)', PRIMARY KEY(`id`)) ENGINE=InnoDB COMMENT='サンプルテーブル';
